version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
      args:
        SERVER_HOST: server
    container_name: web
    environment:
      SERVER_HOST: server
    depends_on:
      - server
    restart: always
    networks:
      - server_net
      - web_net
