/** @type {import('next').NextConfig} */
const ENV = process.env;
const SHORTCUT_ICONS_SERVER_HOST = ENV.SHORTCUT_ICONS_SERVER_HOST;
const ADVERTISE_IMAGE_SERVER_HOST = ENV.ADVERTISE_IMAGE_SERVER_HOST;
const CATEGORY_ICONS_SERVER_HOST = ENV.CATEGORY_ICONS_SERVER_HOST;

module.exports = {
	reactStrictMode: true,
	env: {
		SHORTCUT_ICONS_SERVER_HOST,
		ADVERTISE_IMAGE_SERVER_HOST,
		CATEGORY_ICONS_SERVER_HOST
	},
	images: {
		domains: [
			SHORTCUT_ICONS_SERVER_HOST,
			ADVERTISE_IMAGE_SERVER_HOST,
			CATEGORY_ICONS_SERVER_HOST
		],
	},
}
