FROM node:alpine

WORKDIR /usr/src/app

COPY ./app/package.json .

RUN npm install -g pm2 && npm install -g pnpm && pnpm i

COPY ./app .

RUN mkdir -p ../types

COPY ./types ../types

ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 3000

CMD ["pm2-runtime", "pnpm", "--", "run", "dev"]
