FROM node:18.17.1-alpine

WORKDIR /usr/src/app

COPY ./app/package.json ./app/pnpm-lock.yaml .

RUN npm install -g pm2 && npm install -g pnpm && pnpm i --frozen-lockfile

COPY ./app .

RUN mkdir -p ../types

COPY ./types ../types

ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 3000

CMD ["pm2-runtime", "pnpm", "--", "run", "start"]
