name: docker push

on:
  push:
    branches:
      - main

jobs:
  linting:
    name: Code Linting
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: app
      - name: Run linting
        run: pnpm run lint
        working-directory: app
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit test
        run: echo "Unit test passed!"
        working-directory: app
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.setup-version-tag.outputs.TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Setup version tag
        id: setup-version-tag
        run: echo "TAG=prod-v1.0.$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Compose
        run: |
          export TAG=${{ steps.setup-version-tag.outputs.TAG }}
          echo "TAG=$TAG" >> $GITHUB_ENV
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build --no-cache
          docker-compose up -d
      - name: Run database connection test
        run: |
          MAX_RETRIES=10
          RETRIES=0
          while ! docker exec database mysql -uroot -proot -e "SHOW DATABASES;" > /dev/null 2>&1; do
            RETRIES=$((RETRIES+1))
            if [ $RETRIES -ge $MAX_RETRIES ]; then
              echo "Database connection test failed after $MAX_RETRIES retries."
              exit 1
            fi
            echo "Retrying database connection... Attempt $RETRIES"
            sleep 5
          done
          echo "Database connection test passed!"
      - name: Run nginx test
        run: |
          MAX_RETRIES=10
          RETRIES=0
          while ! curl --silent --fail http://localhost:80 > /dev/null 2>&1; do
            RETRIES=$((RETRIES+1))
            if [ $RETRIES -ge $MAX_RETRIES ]; then
              echo "Nginx test failed after $MAX_RETRIES retries."
              exit 1
            fi
            echo "Retrying nginx connection... Attempt $RETRIES"
            sleep 5
          done
          echo "Nginx test passed!"
      - name: Run E2E Tests
        run: echo "E2E test passed!"
        working-directory: app
      - name: Tear down Docker Compose
        run: docker-compose down
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image
        run: docker-compose push
  deploy-to-staging:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: SSH to GCP Production and deploy
        run: |
          TAG=${{ needs.build-and-push.outputs.TAG }}
          gcloud compute ssh ubereats-production --project=ubereats-447103 --zone=us-central1-b --command="
            git clone https://$GITHUB_TOKEN@github.com/Arvln/ubereats_platform.git
            cd ubereats_platform
            git pull origin main

            export TAG=$TAG
            docker-compose pull
            docker-compose up -d
            docker system prune -a -f
          "
