name: release push

on:
  push:
    branches:
      - 'release*'
  pull_request:
    branches:
      - 'release*'

jobs:
  linting:
    name: Code Linting
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: app
      - name: Run linting
        run: pnpm lint
        working-directory: app
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: app
      - name: Run unit test
        run: pnpm test
        working-directory: app
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.setup-version-tag.outputs.TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Setup version tag
        id: setup-version-tag
        run: echo "TAG=dev-v1.0.$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Compose
        run: |
          export TAG=${{ steps.setup-version-tag.outputs.TAG }}
          echo "TAG=$TAG" >> $GITHUB_ENV
          docker-compose build --no-cache
          docker-compose up -d
      - name: Run database connection test
        run: |
          MAX_RETRIES=10
          RETRIES=0
          while ! docker exec database mysql -uroot -proot -e "SHOW DATABASES;" > /dev/null 2>&1; do
            RETRIES=$((RETRIES+1))
            if [ $RETRIES -ge $MAX_RETRIES ]; then
              echo "Database connection test failed after $MAX_RETRIES retries."
              exit 1
            fi
            echo "Retrying database connection... Attempt $RETRIES"
            sleep 5
          done
          echo "Database connection test passed!"
      - name: Run nginx test
        run: |
          MAX_RETRIES=10
          RETRIES=0
          while ! curl --silent --fail http://localhost:80 > /dev/null 2>&1; do
            RETRIES=$((RETRIES+1))
            if [ $RETRIES -ge $MAX_RETRIES ]; then
              echo "Nginx test failed after $MAX_RETRIES retries."
              exit 1
            fi
            echo "Retrying nginx connection... Attempt $RETRIES"
            sleep 5
          done
          echo "Nginx test passed!"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      - name: Install cypress
        run: pnpm i cypress
      - name: Run E2E Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: app
      - name: Tear down Docker Compose
        run: docker-compose down
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image
        run: docker-compose push
  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Copy environment settings into compute engine
        run: |
          gcloud compute scp docker-compose.cd.yml ubereats-staging:docker-compose.yml --zone=us-central1-f --project=ubereats-447103
          gcloud compute scp --recurse ./docker/mysql/* ubereats-staging:~/mysql --zone=us-central1-f --project=ubereats-447103
      - name: SSH to GCP Staging and deploy
        run: |
          TAG=${{ needs.build-and-push.outputs.TAG }}
          gcloud compute ssh ubereats-staging --project=ubereats-447103 --zone=us-central1-f --command="
            export TAG=$TAG
            docker-compose pull
            docker-compose down -v
            docker-compose up -d
            docker system prune -a -f
          "
  sync_release:
    name: Sync develop code to release branch
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
      - name: Sync latest develop code to release branch
        run: |
          git fetch origin
          git checkout release
          git pull origin develop
          git push origin release
